name: Sync Kernel Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/MotorolaMobilityLLC/kernel-mtk.git

    - name: Fetch upstream commits
      run: git fetch upstream android-14-release-u1tm34.107-34-3

    - name: Checkout new branch from main
      run: git checkout -b new-branch-name master  # Replace new-branch-name with your desired branch name

    - name: Cherry-pick upstream commits
      run: |
        # Fetch a list of commit hashes from the upstream branch
        COMMITS=$(git log upstream/android-14-release-u1tm34.107-34-3 --pretty=format:"%H")
        for commit in $COMMITS; do
          # Cherry-pick each commit
          git cherry-pick $commit || (git cherry-pick --abort && break)
        done

    - name: Push new branch to origin
      run: git push origin new-branch-name  # Push the new branch to your repository

    - name: Clean up
      run: git remote remove upstream
