name: Upstream Kernel

on:
  workflow_dispatch:

jobs:
  upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          git fetch upstream

      - name: Create New Branch
        run: |
          git checkout -b upstream-update-5.10

      - name: Rebase to Upstream 5.10
        run: |
          git rebase upstream/linux-5.10.y

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin upstream-update-5.10 --force
